# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Boston University Society of Asian Scientists and Engineers
email: busase@bu.edu
description: >- # this means to ignore newlines until "baseurl:"
  BU SASE is dedicated to helping Asian heritage scientific and engineering professionals 
  achieve their full potential. We focus on professional development, celebrating diversity, 
  and community contribution while preparing our members for success in the global business world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://busasechapter.org" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: bu_sase
github_username: busase

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Include the _pages directory and make home.html the index
include:
  - _pages
  
# Set home page as the default index
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages/home.html"
    values:
      permalink: /

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Board
    url: /board/
  - title: Alumni
    url: /alumni/
  - title: Events
    url: /events/
  - title: Mentorship
    url: /mentorship/
  - title: Sponsors
    url: /sponsors/
  - title: Sign Up
    url: /signup/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - setup.sh